apiVersion: apps/v1
kind: Deployment
metadata:
  name:  test-mongo
  namespace: default
  labels:
    app:  test-mongo
spec:
  selector:
    matchLabels:
      app: test-mongo
  replicas: 1
  template:
    metadata:
      labels:
        app:  test-mongo
    spec:
      containers:
      - name:  test-mongo
        image:  mongo:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 27017
          name:  test-mongo
      restartPolicy: Always